version: '3.8'

services:
  backend:
    build: ./backend
    container_name: python-server
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
    ports:
      - "80:80"
    volumes:
      - ./backend:/code
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge