services:
  app:
    build: .
    container_name: python-server
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
    ports:
      - 80:80
    volumes:
      - .:/code